// AUTO-GENERATED by seed-template-preview — wraps owner routes for /owner-preview/*
import { useEffect, type ReactNode } from "react";
import { ownerSupabase } from "@/hooks/useOwnerPanel";
import {
  mockReseller, mockResellers, mockPackages, mockLines,
  mockServers, mockVod, mockPanelConfig, mockActiveConnections,
} from "./mockData";

// Build a thenable query result with the right rows for each table.
// Supports the calls actually made by the owner pages.
function makeTable(rows: unknown[]) {
  let result: unknown[] = rows.slice();
  const builder: any = {
    select: (cols?: string) => {
      if (cols && cols.includes("package_id") && rows === mockLines) {
        result = (rows as any[]).map((l) => ({ package_id: l.package_id }));
      }
      return builder;
    },
    insert: () => Promise.resolve({ data: null, error: null }),
    update: () => builder,
    delete: () => builder,
    upsert: () => Promise.resolve({ data: null, error: null }),
    eq:    (col: string, val: unknown) => { result = (result as any[]).filter((r) => r?.[col] === val); return builder; },
    neq:   (col: string, val: unknown) => { result = (result as any[]).filter((r) => r?.[col] !== val); return builder; },
    in:    (col: string, vals: unknown[]) => { result = (result as any[]).filter((r) => vals.includes(r?.[col])); return builder; },
    order: () => builder,
    limit: (n: number) => { result = (result as any[]).slice(0, n); return builder; },
    single:      () => Promise.resolve({ data: (result as any[])[0] ?? null, error: null }),
    maybeSingle: () => Promise.resolve({ data: (result as any[])[0] ?? null, error: null }),
    then: (onFulfilled: (v: { data: unknown; error: null }) => unknown) =>
      Promise.resolve({ data: result, error: null }).then(onFulfilled),
  };
  return builder;
}

const TABLES: Record<string, unknown[]> = {
  resellers:          mockResellers,
  packages:           mockPackages,
  lines:              mockLines,
  servers:            mockServers,
  vod_items:          mockVod,
  panel_config:       mockPanelConfig,
  active_connections: mockActiveConnections,
  streams:            [],
};

let installed = false;
function installMockClient() {
  if (installed) return;
  installed = true;

  // Replace .from() to return mock data; replace auth to report a session.
  (ownerSupabase as any).from = (table: string) => {
    const rows = TABLES[table] ?? [];
    return makeTable(rows);
  };
  (ownerSupabase as any).auth = {
    getSession: () => Promise.resolve({ data: { session: { user: { email: mockReseller.email } } }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    signInWithPassword: () => Promise.resolve({ data: null, error: null }),
    signOut: () => Promise.resolve({ error: null }),
  };
}

// Install at module evaluation so children render with mock from first paint.
installMockClient();

export function PreviewProvider({ children }: { children: ReactNode }) {
  useEffect(() => {
    document.title = "Vista previa — Mi Panel IPTV";
  }, []);

  return (
    <div className="relative min-h-screen">
      <div className="sticky top-0 z-50 bg-amber-50 border-b border-amber-200 text-amber-800 text-xs px-4 py-1.5 text-center font-medium">
        🧪 Modo vista previa — datos ficticios, sin conexión a base de datos real
      </div>
      {children}
    </div>
  );
}
